---
title: "Random Forest"
author: "ASO"
date: "10/5/2019"
output:
  html_document: default
  pdf_document: default
---

Conexión con postgres
```{r}
#install.packages("RPostgreSQL")
require("RPostgreSQL")

# Guardar el Password para poder posteriormente eliminarlo
pw <- { "1796vd"}

# Leer el driver de PostgreSQL
drv <- dbDriver("PostgreSQL")

# Crear la conexion con la base de datos
con <- dbConnect(drv, dbname = "postgres",
                 host = "localhost", port = 5432,
                 user = "postgres", password = pw)
# Eliminar el Password
rm(pw) 

# Chequear que existe la tabla de la base de datos para comprobar la conexión
dbExistsTable(con, "descripcion_carnet")

```

Importo los paquetes más genéricos
```{r}
library(readr)
library(ISLR)
library(ggplot2)
library(caret)
library(dplyr)
library(magrittr)
library(tidyverse)
library(rpart)
library(randomForest)
library(rpart.plot)
```

Importo la data de victimas
```{r}
victima <- dbGetQuery(con, "SELECT * FROM victima_involucrada")
head(victima)
```

Importo el resto de tablas relacionadas con victimas
```{r}
tipologia <-dbGetQuery(con, "SELECT * FROM descripcion_tipologia_victima")
head(tipologia)
```

```{r}
sexo <-dbGetQuery(con, "SELECT * FROM descripcion_sexo_victima")
head(sexo)
```

```{r}
responsabilidadpeaton <-dbGetQuery(con, "SELECT * FROM descripcion_responsabilidad_peaton")
head(responsabilidadpeaton)
```

```{r}
condicionfisica <-dbGetQuery(con, "SELECT * FROM descripcion_condicion_fisica_victima")
head(condicionfisica)
```



Combino las tablas

```{r}
datos1 <- merge(x = victima, y = responsabilidadpeaton, by = "id_desc_responsabilidad_peaton", all = TRUE)
names(datos1)
```

```{r}
datos2 <- merge(x = datos1, y = sexo, by = "id_desc_sexo", all = TRUE)
names(datos2)
```

```{r}
datos3 <- merge(x = datos2, y = condicionfisica, by = "id_desc_condicion_fisica", all = TRUE)
names(datos3)
```

```{r}
datos4 <- merge(x = datos3, y = tipologia , by = "id_desc_tipo_victima", all = TRUE)
names(datos4)
```

Comprobación

```{r}
head(datos4)
```

```{r}
dim(datos4)
```

Nos quedamos con las columnas que vamos a trabajar

```{r}
datos5<- datos4[,c("edad", "num_expediente", "desc_condicion_fisica", "desc_responsabilidad_peaton", "desc_sexo", "desc_tipologia")]
head(datos5)
```


Agrupación
```{r}
datos6 <- datos5 %>%
  group_by(edad, desc_condicion_fisica, desc_responsabilidad_peaton, desc_sexo, desc_tipologia) %>%
  summarise(cantvictimas=n())
datos6
```


Partimos el dataset en 2 grupos: entrenamiento y validación 
```{r}
set.seed(12)
n = nrow(datos6) 
n
frac_train <- .70
mascara <- sample(c(rep("train", 3343), rep("test", n -3343)), n)
entrevali <- split(datos6, mascara)
entrevali$train
```


```{r}
model.rf <- randomForest(formula = cantvictimas ~ edad, importance = TRUE ,data = entrevali$train)
varImpPlot(model.rf)
plot(model.rf$predicted)
```

```{r}
preds <- predict(model.rf,data = entrevali$train)
real <- entrevali$train$cantvictimas
plot(real, preds)

summary 

RMSE <- sqrt(mean((real - preds)^2))
RMSE

```





